Adiciona a caixa amarela contendo lista de documentos relacionados quando não foi gerada pelo packtools
scieloorg/opac pull request #2524
Opened 2022-12-04 14:23 UTC by robertatakenaka

#### O que esse PR faz?
Adiciona a caixa amarela contendo lista de documentos relacionados quando não foi gerada pelo packtools

#### Onde a revisão poderia começar?
por commits

#### Como este poderia ser testado manualmente?
Acessando a página do artigo que tem errata, ou que tem comentários, que tem errata, pois geralmente não foi inserida a tag related-article neste tipo de documento.

#### Algum cenário de contexto que queira dar?
Foi sugerido que passassem a inserir a tag. Este código deve funcionar para ambas as situações.

### Screenshots
n/a

#### Quais são tickets relevantes?
#2389 
#2424
#2352

### Referências
n/a

2022-12-04 18:37 UTC, gitnnolabs commented
@robertatakenaka não é bloqueante, mas não está traduzido o texto: **Esta errata corrige**

<img width="1248" alt="Screen Shot 2022-12-04 at 15 08 35" src="https://user-images.githubusercontent.com/86991526/205507912-e1b17270-3861-48ed-b1c3-43924d20428d.png">

Mas olhando outro documentos de errata percebi que está duplicando as msgs, veja: 
<img width="871" alt="Screen Shot 2022-12-04 at 15 34 42" src="https://user-images.githubusercontent.com/86991526/205509053-c5752e6a-01c0-4023-bcd2-391cf33ee0f2.png">
<img width="915" alt="Screen Shot 2022-12-04 at 15 34 47" src="https://user-images.githubusercontent.com/86991526/205509055-ee435aaf-6402-44e8-84ca-3d1bad793d9a.png">


Link para esse exemplo: http://www.scielo.br/j/rbee/a/c9fNxmwZ89FJtP6hBfdcS8t/

Sugiro que seja corrigido para que seja aprovado.

2022-12-04 18:39 UTC, gitnnolabs requested changes
Sugiro correção pra que não haja duplicidades de identificação dos documentos corrigidos.

2022-12-04 19:30 UTC, robertatakenaka commented
@gitnnolabs correção feita no packtools https://github.com/scieloorg/packtools/pull/355

2022-12-06 15:12 UTC, gitnnolabs commented
@robertatakenaka 

Estou validando e acho que entendi a lógica, mas suspeito que esteja errada. 

A consequência dessa lógica é que aparece duas caixas, vejam nos meus testes: 

![Captura de Tela 2022-12-06 às 11 52 18](https://user-images.githubusercontent.com/86991526/205945330-f4f5c689-ad60-40c3-a667-70894554fdfe.png)

No trecho: 

```python
<!-- xxx Verifica se o artigo contém artigos relacionados -->
{% if article.related_articles %}
<script>
    if (document.querySelectorAll(".related-panel").length == 1) {
        // somente há o related-panel do site
        // não há o related-panel inserido pelo packtools
        $('.articleBadge-editionMeta-doi-copyLink').append($('.related-panel').html())
    }
</script>
{% endif %} 
```

Aqui ```document.querySelectorAll(".related-panel").length == 1``` está verificando se existe um **related-panel** 

Não é possível ter uma lógica avaliando a existência do **related-panel**, por que nesse caso irá sempre duplicar as caixas. 

Sugiro que seja avaliado se já exista um elemento com "article-correction-title", por que ai nesse caso temos certeza que o packtool já adicionou a caixa com os relacionados. 

Portanto, a lógica ficaria assim: 

```python 
<script>
    // Se não existe um elemento no HTML com a classe 'article-correction-title' é por que o packtools não adicionou uma caixa com os relacionados.
    if (document.querySelectorAll(".article-correction-title").length == 0) {
        //Ai passamos a exibir o related-panel gerado a partir da base de dados.
        $('.articleBadge-editionMeta-doi-copyLink').append($('.related-panel').html())
    }
</script>
```

2022-12-06 20:23 UTC, robertatakenaka commented
@jamilatta correções efetuadas

2022-12-07 09:06 UTC, gitnnolabs commented
Revalidando....

2022-12-07 20:14 UTC, merged

2022-12-07 20:15 UTC, gitnnolabs commented
Funcionado como esperado!!! @robertatakenaka